name: release
on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: (lint commit) check all commits
        uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '14'

      - name: install dependencies with yarn
        shell: bash
        run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline

      - name: run lint
        run: yarn lint

      - name: run test
        run: yarn test

      - name: run build
        run: yarn build

      - name: release project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'efishery-sre'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'engineer@efishery.com'
          GIT_COMMITTER_EMAIL: 'engineer@efishery.com'
          GIT_AUTHOR_NAME: '@efishery-sre'
          GIT_COMMITTER_NAME: '@eFishery-sre'
        run: yarn release
